services:
  database:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    networks:
      - ufrojobs-network
    volumes:
      - database-data:/var/lib/postgresql/data
    env_file:
      - ./.env.db
  minios3:
      image: minio/minio:latest
      restart: always  
      ports:
        - "9000:9000"
        - "9001:9001"
      command: server /data --console-address ":9001"
      volumes:
        - minios3-data:/data
      env_file:
        - ./.env.minio
      networks:
        - ufrojobs-network
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./.env.rabbit
    networks:
      - ufrojobs-network
  api:
    build: .
    restart: always
    ports: 
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - database
      - minios3
      - rabbitmq
    networks:
      - ufrojobs-network
  
  prometheus-init:
    image: alpine:latest
    container_name: prometheus_init
    env_file:
      - ./.env.prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml.template
      - prometheus_conf:/etc/prometheus
    command: >
      sh -c "apk add --no-cache gettext 
      && envsubst < /etc/prometheus/prometheus.yml.template > /etc/prometheus/prometheus.yml"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver 
    volumes:
      - prometheus_conf:/etc/prometheus
    networks:
      - ufrojobs-network
    depends_on:
      prometheus-init:
        condition: service_completed_successfully

 
  grafana:
    image: grafana/grafana:latest
    container_name: ufrojobs_grafana
    ports:
      - "3001:3000" 
    env_file:
      - ./.env.grafana
    depends_on:
      - prometheus
    networks:
      - ufrojobs-network

  k6:
    image: grafana/k6:latest
    networks:
      - ufrojobs-network
    volumes:
      - ./:/scripts 
    command: version
    
networks:
  ufrojobs-network:
    driver: bridge
volumes:
  database-data:
    driver: local
  minios3-data:
    driver: local
  prometheus_conf:
    driver: local